### PR TITLE
fix: fixed stuck token metadata updates

### LINKED ISSUE #27: Resolved metadata not being saved into DB
There seems to be a logic bug in the code ref: https://github.com/dipdup-net/metadata/blob/d2ec49730fa5a32039eb493ac64aadb90546daea/cmd/metadata/service/token.go#L161

This line forces the saver function to only save the metadata if there are at least 10 pending tokens which cause the metadata to be not stored at all until this condition is met. This is problematic in many ways, especially for contracts that don't have that high frequency of token mints. This also affects any previously unresolved/failed token mints which can also be blocked on this condition. 

A easy fix would be to go back to the previous code where there was a separate case with a ticker that would autosave the data after some amount of time irrespective of the token count

### PR DESCRIPTION
**Pull request by gdsoumya**
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>

This PR adds a periodic database update in saver() to prevent metadata updates from being stuck while this condition isn't met https://github.com/dipdup-net/metadata/blob/d2ec49730fa5a32039eb493ac64aadb90546daea/cmd/metadata/service/token.go#L161
 
Fixes #27

### CODE REVIEW

File: cmd/metadata/service/token.go [hunk 1]
```diff
@@ -167,6 +170,35 @@ func (s *TokenService) saver(ctx context.Context) {
 				continue
 			}
 
+			for i := range tokens {
```
Comment (aopoltorzhicky) [inline cmd/metadata/service/token.go]: Looks like you can make a function here to avoid duplicated code. It's a copy-pasted part from another case section.

Comment (gdsoumya) [reply cmd/metadata/service/token.go]: done

Comment (aopoltorzhicky) [reply cmd/metadata/service/token.go]: Great! Thanks for PR!
